### ISSUE TITLE
Need to add handler for "number_reference" blocks

### ISSUE THREAD

**Issue by kerimoyle** [hsorby/vue-sphinx-xml#9]
![image](https://user-images.githubusercontent.com/46887220/106082008-cdb69280-617e-11eb-9746-7e51713c6580.png)

**Comment by hsorby** [comment]
To resolve this it would be best to create a pull request agains [example-vue-sphinx-xml](https://github.com/hsorby/example-vue-sphinx-xml) with some of this content contained that would make things a lot easier to fix.

**Comment by kerimoyle** [comment]
It's ok, I'll fix it next week.  This is just a reminder of things to do!

**Comment by hsorby** [comment]
[example-vue-sphinx-xml](https://github.com/hsorby/example-vue-sphinx-xml) is the "test" for this repository so I really would like to see this element type in there.
